import { shallowMount, createLocalVue } from "@vue/test-utils";
import BootstrapVue from "bootstrap-vue";
import FilterReport from "@/components/organisms/report/_shared/FilterReport";
import { VEHICLE_RETURN } from "./mock";
import Vuelidate from "vuelidate";

const localVue = createLocalVue();
localVue.use(BootstrapVue);
localVue.use(Vuelidate);

let wrapper;
const id = "income";
let mocks = {
  $router: {
    push() {},
  },
  $utility: {
    getSpotId: () => "mocked-spot",
    formatDateMoment: () => {},
    setErrorContextSentry: () => {},
    getOptionProductMembership: () => {
      return [
        {
          name: "product-mocked-name",
          id: "product-mocked-id",
        },
      ];
    },
    getVehicle: () => {
      return VEHICLE_RETURN;
    },
  },
  $sentry: {
    captureMessage() {},
  },
};

describe("ui.FilterReport.vue", () => {
  let mocksFn = {};

  beforeEach(() => {
    mocksFn = {};
    wrapper = shallowMount(FilterReport, {
      localVue,
      mocks,
      propsData: { id },
    });
  });

  afterEach(() => {
    jest.restoreAllMocks();
    jest.clearAllMocks();
  });

  test("test rendering officer field with helper loading is true, shouldnt render it", async () => {
    await wrapper.vm.$nextTick();
    wrapper.setProps({
      has_officer: true,
    });
    wrapper.vm.helper.loading.officer = true;
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.find(`[data-testid="wrapper-caption_loading-officer"]`).exists()
    ).toEqual(true);
  });
  test("test rendering officer field with helper loading is false, should render it", async () => {
    await wrapper.vm.$nextTick();
    wrapper.setProps({
      has_officer: true,
    });
    wrapper.vm.helper.loading.officer = false;
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.find(`[data-testid="wrapper-caption_loading-officer"]`).exists()
    ).toEqual(false);
  });
  test("test rendering user field with helper loading is true, shouldnt render it", async () => {
    await wrapper.vm.$nextTick();
    wrapper.setProps({
      has_user: true,
    });
    wrapper.vm.helper.loading.user = true;
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.find(`[data-testid="wrapper-caption_loading-user"]`).exists()
    ).toEqual(true);
  });
  test("test rendering user field with helper loading is false, should render it", async () => {
    await wrapper.vm.$nextTick();
    wrapper.setProps({
      has_user: true,
    });
    wrapper.vm.helper.loading.user = false;
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.find(`[data-testid="wrapper-caption_loading-user"]`).exists()
    ).toEqual(false);
  });

  describe("filter-report__leave", () => {
    it.each([
      {
        case: "given has_leave_type false, shouldn't exist",
        exists: false,
        has_leave_type: false,
      },
      {
        case: "given has_leave_type true, should exist",
        exists: true,
        has_leave_type: true,
      },
    ])("$case", async ({ exists, has_leave_type }) => {
      wrapper.setProps({ has_leave_type });
      await wrapper.vm.$nextTick();

      const filterLeave = wrapper.find(
        `[data-testid="filter-report__${id}-leave"]`
      );
      expect(filterLeave.exists()).toBe(exists);
    });

    describe("filter-opt-leave-type", () => {
      it.each([
        {
          case: "given has_leave_type false, shouldn't exist",
          exists: false,
          has_leave_type: false,
        },
        {
          case: "given has_leave_type true, should exist",
          exists: true,
          has_leave_type: true,
        },
      ])("$case", async ({ exists, has_leave_type }) => {
        wrapper.setProps({ has_leave_type });
        await wrapper.vm.$nextTick();

        const inputLeaveType = wrapper.findComponent({
          ref: `filter-opt-leave-type__${id}`,
        });
        expect(inputLeaveType.exists()).toBe(exists);
      });
    });

    describe("filter-opt-leave-reason", () => {
      it.each([
        { case: "given has_leave_type false, shouldn't exist", exists: false, has_leave_type: false, leave_reason_option: [] },
        { case: "given has_leave_type true and option.leave_reason empty, shouldn't exist", exists: false, has_leave_type: false, leave_reason_option: [] },
        {
          case: "given has_leave_type true and option.leave_reason filled, should exist", exists: true, has_leave_type: true,
          leave_reason_option: [{ text: "Keluarga", value: "FAMILY", type: "PERMISSION" }]
        },
      ])("$case", async ({ exists, has_leave_type, leave_reason_option }) => {
        wrapper.setProps({ has_leave_type })
        wrapper.vm.options.leave_reason = leave_reason_option
        await wrapper.vm.$nextTick()

        const inputLeaveReason = wrapper.findComponent({ ref: `filter-opt-leave-reason__${id}` })
        expect(inputLeaveReason.exists()).toBe(exists)
      })
    })
  })

  it.each([
    {
      case: "not having any props, should not renderin anything",
      props: {},
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_period is true, should render period field",
      props: { has_period: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": true,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_date is true, should render date field",
      props: { has_date: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": true,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_time_range is true, should render duration field",
      props: { has_time_range: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": true,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_location is true, should render location field",
      props: { has_location: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": true,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_column_setting is true but not having column options, should render column field and blank filter",
      props: { has_column_setting: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": true,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": true,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_column_setting is true and having column options, should render column field and filter options list",
      props: { has_column_setting: true, option_column: ["mocked"] },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": true,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": true,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_administration is true and having administration type options, should render administration type field and filter options list",
      props: { has_administration_type: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: ["mocked"],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": true,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": true,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_service is true but not having service options, should render service field and blank filter",
      props: { has_service: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": true,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": true,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_service is true and having service options, should render service field and filter options list",
      props: { has_service: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: ["mocked"],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": true,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": true,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_vehicle is true but not having vehicle options, should render vehicle field and blank filter",
      props: { has_vehicle: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": true,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": true,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_vehicle is true and having vehicle options, should render vehicle field and filter options list",
      props: { has_vehicle: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: ["mocked"],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": true,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": true,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_product is true but not having product options, should render product field and blank filter",
      props: { has_product: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": true,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": true,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_product is true and having product options, should render product field and filter options list",
      props: { has_product: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: ["mocked"],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": true,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": true,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_reason is true but not having reason options, should render reason field and blank filter",
      props: { has_reason: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": true,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": true,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_reason is true and having reason options, should render reason field and filter options list",
      props: { has_reason: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: ["mocked"],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": true,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": true,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_transaction_status is true but not having transaction status options, should render transaction status field and blank filter",
      props: { has_transaction_status: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": true,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": true,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_transaction_status is true and having transaction status options, should render transaction status field and filter options list",
      props: { has_transaction_status: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: ["mocked"],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": true,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": true,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_transaction_type is true but not having transaction type options, should render transaction type field and blank filter",
      props: { has_transaction_type: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": true,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": true,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_transaction_type is true and having transaction type options, should render transaction type field and filter options list",
      props: { has_transaction_type: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: ["mocked"],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": true,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": true,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_gate_type is true but not having gate type options, should render gate type field and blank filter",
      props: { has_gate_type: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": true,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": true,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_gate_type is true and having gate type options, should render gate type field and filter options list",
      props: { has_gate_type: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: ["mocked"],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": true,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": true,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_shift is true but not having shift options, should render shift field and blank filter",
      props: { has_shift: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": true,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": true,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_shift is true and having shift options, should render shift field and filter options list",
      props: { has_shift: true },
      optionList: {
        shift: ["mocked"],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": true,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": true,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_type is true but not having type options, should render type field and blank filter",
      props: { has_type: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": true,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": true,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_type is true and having type options, should render type field and filter options list",
      props: { has_type: true },
      optionList: {
        shift: [],
        type: ["mocked"],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": true,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": true,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_pos is true but not having station options, should render station field and blank filter",
      props: { has_pos: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": true,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": true,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
    {
      case: "with props has_pos is true and having station options, should render station field and filter options list",
      props: { has_pos: true },
      optionList: {
        shift: [],
        type: [],
        pos: ["mocked"],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": false,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": true,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": true,
      },
    },
    {
      case: "with props has_date_range is true, should render filter-report__income-date-range",
      props: { has_date_range: true },
      optionList: {
        shift: [],
        type: [],
        pos: [],
        administration_type: [],
        transaction_status: [],
        reason: [],
        transaction_type: [],
        gate_type: [],
        vehicle: [],
        user: [],
        officer: [],
        product: [],
        service: [],
        location: [],
      },
      componentVisibility: {
        "filter-report__income-period": false,
        "filter-report__income-date": false,
        "filter-report__income-date-range": true,
        "filter-report__income-duration": false,
        "filter-report__income-location": false,
        "filter-report__income-column": false,
        "filter-report__income-administration-type": false,
        "filter-report__income-service": false,
        "filter-report__income-vehicle": false,
        "filter-report__income-product": false,
        "filter-report__income-reason": false,
        "filter-report__income-transaction-status": false,
        "filter-report__income-transaction-type": false,
        "filter-report__income-gate_type": false,
        "filter-report__income-user": false,
        "filter-report__income-officer": false,
        "filter-report__income-shift": false,
        "filter-report__income-report-type": false,
        "filter-report__income-station": false,
        "blank-filter-column__income": false,
        "blank-filter-service__income": false,
        "blank-filter-vehicle__income": false,
        "blank-filter-product__income": false,
        "blank-filter-reason__income": false,
        "blank-filter-transaction_status__income": false,
        "blank-filter-transaction_type__income": false,
        "blank-filter-gate_type__income": false,
        "blank-filter-shift__income": false,
        "blank-filter-type__income": false,
        "blank-filter-station__income": false,
        "filter-opt-column__income": false,
        "filter-opt-administration_type__income": false,
        "filter-opt-service__income": false,
        "filter-opt-vehicle__income": false,
        "filter-opt-product__income": false,
        "filter-opt-reason__income": false,
        "filter-opt-transaction_status__income": false,
        "filter-opt-transaction_type__income": false,
        "filter-opt-gate_type__income": false,
        "filter-opt-shift__income": false,
        "filter-opt-type__income": false,
        "filter-opt-station__income": false,
      },
    },
  ])("$case", async (data) => {
    wrapper.setProps(data.props);
    wrapper.setData({
      options: data.optionList,
      modal: { modal_filter: true },
      helper: { gate_type: data.props.has_gate_type },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    for (const [key, value] of Object.entries(data.componentVisibility)) {
      expect(wrapper.findComponent({ ref: `${key}` }).exists()).toBe(value);
    }
  });

  describe("test filter report timezone", () => {
    test.each([
      {
        case: "given has_timezone true, should exist",
        has_timezone: true,
        exists: true,
      },
      {
        case: "given has_timezone false, shouldn't exist",
        has_timezone: false,
        exists: false,
      },
    ])("$case", async ({ has_timezone, exists }) => {
      wrapper.setProps({ has_timezone });
      await wrapper.vm.$nextTick();

      const filter = wrapper.find(`#filter-report__${id}-timezone`);
      expect(filter.exists()).toBe(exists);
    });
  });

  test("test click link vehicle type, should call function router push with arguments /spots/edit/?pane=vehicle", async () => {
    wrapper.vm.$router.push = mocksFn["routerPush"] = jest.fn();
    wrapper.setData({
      options: {
        vehicle: [],
      },
      modal: { modal_filter: true },
    });
    wrapper.setProps({ has_vehicle: true });
    await wrapper.vm.$nextTick();
    wrapper
      .findComponent({ ref: "blank-filter-vehicle__income" })
      .trigger("click");
    await wrapper.vm.$nextTick();
    expect(mocksFn["routerPush"]).toHaveBeenCalled();
    expect(mocksFn["routerPush"].mock.calls[0][0]).toEqual(
      "/spots/edit/?pane=vehicle"
    );
  });

  test("test click add product, should call function router push with arguments spots/product", async () => {
    wrapper.vm.$router.push = mocksFn["routerPush"] = jest.fn();
    wrapper.setData({
      options: {
        product: [],
      },
      modal: { modal_filter: true },
    });
    wrapper.setProps({ has_product: true });
    await wrapper.vm.$nextTick();
    wrapper
      .findComponent({ ref: "blank-filter-product__income" })
      .trigger("click");
    await wrapper.vm.$nextTick();
    expect(mocksFn["routerPush"]).toHaveBeenCalled();
    expect(mocksFn["routerPush"].mock.calls[0][0]).toEqual("/spots/product");
  });

  test("test rendering option product when product options length is less than 5, should render checkbox option type", async () => {
    wrapper.setProps({
      has_product: true,
    });
    wrapper.setData({
      options: {
        product: [{ text: "mocked-1", value: "mocked-1" }],
      },
      modal: { modal_filter: true },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.findComponent({ ref: "filter-opt-product__income" }).exists()
    ).toBe(true);
  });
  test("test rendering option product when product options length is more than 5, should render select option type", async () => {
    wrapper.setProps({
      has_product: true,
    });
    wrapper.setData({
      options: {
        product: [
          { text: "mocked-1", value: "mocked-1" },
          { text: "mocked-2", value: "mocked-2" },
          { text: "mocked-3", value: "mocked-3" },
          { text: "mocked-4", value: "mocked-4" },
          { text: "mocked-5", value: "mocked-5" },
          { text: "mocked-6", value: "mocked-6" },
        ],
      },
      modal: { modal_filter: true },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.findComponent({ ref: "filter-select-product__income" }).exists()
    ).toBe(true);
  });
  test("test rendering option vehicle when vehicle options length is less than 5, should render checkbox option type", async () => {
    wrapper.setProps({
      has_vehicle: true,
    });
    wrapper.setData({
      options: {
        vehicle: [{ text: "mocked-1", value: "mocked-1" }],
      },
      modal: { modal_filter: true },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.findComponent({ ref: "filter-select-vehicle__income" }).exists()
    ).toBe(false);
    expect(
      wrapper.findComponent({ ref: "filter-opt-vehicle__income-0" }).exists()
    ).toBe(true);
  });
  test("test rendering option vehicle when vehicle options length is more than 5, should render select option type", async () => {
    wrapper.setProps({
      has_vehicle: true,
    });
    wrapper.setData({
      options: {
        vehicle: [
          { text: "mocked-1", value: "mocked-1" },
          { text: "mocked-2", value: "mocked-2" },
          { text: "mocked-3", value: "mocked-3" },
          { text: "mocked-4", value: "mocked-4" },
          { text: "mocked-5", value: "mocked-5" },
          { text: "mocked-6", value: "mocked-6" },
        ],
      },
      modal: { modal_filter: true },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.findComponent({ ref: "filter-select-vehicle__income" }).exists()
    ).toBe(true);
    expect(
      wrapper.findComponent({ ref: "filter-opt-vehicle__income-0" }).exists()
    ).toBe(false);
  });
  test("test rendering option column list when column list options length is less than 5, should render checkbox option type", async () => {
    wrapper.setProps({
      has_column_setting: true,
      option_column: [{ text: "mocked-1", value: "mocked-1" }],
    });
    wrapper.setData({
      modal: { modal_filter: true },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.findComponent({ ref: "filter-select-column__income" }).exists()
    ).toBe(false);
    expect(
      wrapper.findComponent({ ref: "filter-opt-column__income-0" }).exists()
    ).toBe(true);
  });
  test("test rendering option column list when column list options length is more than 5, should render select option type", async () => {
    wrapper.setProps({
      has_column_setting: true,
      option_column: [
        { text: "mocked-1", value: "mocked-1" },
        { text: "mocked-2", value: "mocked-2" },
        { text: "mocked-3", value: "mocked-3" },
        { text: "mocked-4", value: "mocked-4" },
        { text: "mocked-5", value: "mocked-5" },
        { text: "mocked-6", value: "mocked-6" },
      ],
    });
    wrapper.setData({
      modal: { modal_filter: true },
    });
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    expect(
      wrapper.findComponent({ ref: "filter-select-column__income" }).exists()
    ).toBe(true);
    expect(
      wrapper.findComponent({ ref: "filter-opt-column__income-0" }).exists()
    ).toBe(false);
  });

  describe("test rendering select all or deselect all", () => {
    it.each([
      {
        case: "wasn't selected all column, should render select all column ",
        componentVisibility: {
          "btn-select-all-column__income": true,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: true,
          option_column: ["mocked"],
        },
        data: {
          column: [],
          options: {},
        },
      },
      {
        case: "wasn't selected all location, should render select all location ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          location: [],
          options: {
            location: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "wasn't selected all vehicle, should render select all vehicle ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": true,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: true,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          vehicle: [],
          options: {
            vehicle: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "wasn't selected all product, should render select all product ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          product: [],
          options: {
            product: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "wasn't selected all user, should render select all user ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          user: [],
          options: {
            user: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "wasn't selected all officer, should render select all officer ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          officer: [],
          options: {
            officer: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "was selected all column, should render clear all column ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": true,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: true,
          option_column: [{ text: "mocked", value: "mocked" }],
        },
        data: {
          column: [{ text: "mocked", value: "mocked" }],
          options: {},
        },
      },
      {
        case: "was selected all location, should render clear all location ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
          "btn-clear-all-vehicle__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          location: [{ text: "mocked", value: "mocked" }],
          options: {
            location: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "was selected all vehicle, should render clear all vehicle ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-vehicle__income": true,
          "btn-clear-all-column__income": false,
        },
        props: {
          has_vehicle: true,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          vehicle: [{ text: "mocked", value: "mocked" }],
          options: {
            vehicle: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "was selected all product, should render clear all product ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          product: [{ text: "mocked", value: "mocked" }],
          options: {
            product: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "was selected all user, should render clear all user ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          user: [{ text: "mocked", value: "mocked" }],
          options: {
            user: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
      {
        case: "was selected all officer, should render clear all officer ",
        componentVisibility: {
          "btn-select-all-column__income": false,
          "btn-select-all-vehicle__income": false,
          "btn-clear-all-vehicle__income": false,
          "btn-clear-all-column__income": false,
        },
        props: {
          has_vehicle: false,
          has_column_setting: false,
          option_column: [],
        },
        data: {
          officer: [{ text: "mocked", value: "mocked" }],
          options: {
            officer: [{ text: "mocked", value: "mocked" }],
          },
        },
      },
    ])("$case", async (data) => {
      wrapper.setProps({
        ...data.props,
      });
      await wrapper.vm.$nextTick();
      wrapper.setData({
        ...data.data,
      });
      await wrapper.vm.$nextTick();
      await wrapper.vm.$nextTick();
      await wrapper.vm.$nextTick();
      for (const [key, value] of Object.entries(data.componentVisibility)) {
        expect(wrapper.findComponent({ ref: `${key}` }).exists()).toBe(value);
      }
    });
  });

  test("test rendering prefix product when has_non_member are true and value prefix are NON_MEMBER, should render", async () => {
    wrapper.setProps({
      has_product: true,
      has_non_member: true,
    });
    await wrapper.vm.$nextTick();
    wrapper.vm.helper.prefix_product = "NON_MEMBER";
    wrapper.vm.options.product = ["mocked"];
    await wrapper.vm.$nextTick();
    expect(
      wrapper.find(`[data-testid="wrapper-filter-product__income"]`).exists()
    ).toEqual(false);
    expect(
      wrapper.findComponent({ ref: "prefix-opt-product__income" }).exists()
    ).toEqual(true);
  });

  test("test rendering prefix product when has_non_member are true and value prefix are MEMBER, shouldnt render", async () => {
    wrapper.setProps({
      has_product: true,
      has_non_member: true,
    });
    await wrapper.vm.$nextTick();
    wrapper.vm.helper.prefix_product = "MEMBER";
    wrapper.vm.options.product = ["mocked"];
    await wrapper.vm.$nextTick();
    expect(
      wrapper.find(`[data-testid="wrapper-filter-product__income"]`).exists()
    ).toEqual(true);
    expect(
      wrapper.findComponent({ ref: "prefix-opt-product__income" }).exists()
    ).toEqual(true);
  });
});
